### ISSUE TITLE
Lightness wheel event firing issue

### ISSUE THREAD

**Issue by faisalt** [epistemex/huewheel#1]
When the brightness wheel is set to clickable (lightnessRingClickable), the change event does not get fired when you click once, hence you either need to click twice on the brightness wheel, or click the wheel and then change the colour (or alternatively dragging works fine).

I found a way around this by adding in a 'sendEvent()' in the huewheel.js file (line 137):

```javascript
/*
* Check if in LIGHTNESS RING
*/
else if (lightClickable && d > lr - lumaThickness * 0.5 && d < lr + lumaThickness * 0.5) { 
    var ta = a * r2d - 90;
    if (ta < 0) ta += 360;
    me.hsl(angle, saturation, ta / 360)
    //Added in sendEvent call to allow event firing when clicking on brightness ring.
    sendEvent();
}
```

**Comment by epistemex** [comment]
Thanks @faisalt. Prior to v1.1.4 the sendevent was centralized. But due to recursivness in the onChange handler in some special cases it had be separated out. The solution is indeed to use a sendEvent() from the check.
