### ISSUE TITLE
Color wheel so awesome!

### ISSUE THREAD

**Issue by Noitidart** [epistemex/huewheel#2]
Your color wheel is soooo awesome!! Do you have a simple copy-paste thing I can drop? I wasn't going for cross-browser, just firefox only for an addon I was making. Thank you soo much! Your color wheel I saw it a long time ago (months) but stuck in my head since then it would be so great if I can use this too please

**Comment by epistemex** [comment]
Thanks Noitidart, much appreciated. There is no paste version unfortunately. I guess you could use the [minimized](https://github.com/epistemex/huewheel/blob/master/huewheel.min.js) version but I would rather recommend setting up an environment that allows you to merge and minimize your JavaScript files into a single one. My 2 cents..
